IRIS: Link Class Reference
Link Class Reference
#include <link.h>
Public Member Functions
Link (int srcComponentId, int linkWidth)
void Send (uint64_t data, int srcComponentId)
Public Attributes
int src
int width
list< OutputBase * > outputs
Detailed Description
Definition at line 35 of file link.h.
Constructor & Destructor Documentation
Link::Link (int srcComponentId, int linkWidth)
Definition at line 6 of file link.cc.
References Component::addOutputLink(), Simulator::getComponentDesc(), ComponentDescription::lpId, Simulator::MyRank(), ComponentDescription::ptr, src, and width.
Member Function Documentation
void Link::Send (uint64_t data, int srcComponentId)
Definition at line 19 of file link.cc.
References OutputBase::CallHandler(), Simulator::getComponentDesc(), ComponentDescription::lpId, Simulator::MyRank(), Simulator::Now(), outputs, and Simulator::Schedule().
Member Data Documentation
list<OutputBase*> Link::outputs
Definition at line 42 of file link.h.
Referenced by addOutput(), and Send().
int Link::src
Definition at line 39 of file link.h.
Referenced by Link().
int Link::width
Definition at line 40 of file link.h.
Referenced by Link().
The documentation for this class was generated from the following files:
link.h
link.cc