IRIS: GenericLink Class Reference
GenericLink Class Reference
#include <genericLink.h>
Public Member Functions
GenericLink ()
~GenericLink ()
void setup ()
void process_event (IrisEvent *e)
string toString () const
string print_stats () const
ullint get_flits_utilization ()
ullint get_credits_utilization ()
Public Attributes
uint cycles
uint stages
ullint flits_passed
ullint credits_passed
uint link_id
bool is_dateline
Private Member Functions
void handle_link_arrival_event (IrisEvent *e)
Private Attributes
uint node_ip
Detailed Description
Definition at line 33 of file genericLink.h.
Constructor & Destructor Documentation
GenericLink::GenericLink () [inline]
Definition at line 36 of file genericLink.h.
GenericLink::~GenericLink () [inline]
Definition at line 37 of file genericLink.h.
Member Function Documentation
ullint GenericLink::get_credits_utilization ()
Definition at line 111 of file genericLink.cc.
References credits_passed.
ullint GenericLink::get_flits_utilization ()
Definition at line 105 of file genericLink.cc.
References flits_passed.
void GenericLink::handle_link_arrival_event (IrisEvent * e) [private]
Definition at line 52 of file genericLink.cc.
References _DBG, NetworkComponent::address, credits_passed, data, IrisEvent::dst_id, IrisEvent::event_data, flits_passed, IrisLink::input_connection, Simulator::Now(), IrisLink::output_connection, NetworkComponent::process_event(), Simulator::Schedule(), IrisEvent::src_id, LinkArrivalData::type, and LinkArrivalData::vc.
Referenced by process_event().
string GenericLink::print_stats (void) const
Definition at line 91 of file genericLink.cc.
References NetworkComponent::address, credits_passed, flits_passed, and toString().
void GenericLink::process_event (IrisEvent * e) [virtual]
Implements IrisLink.
Definition at line 36 of file genericLink.cc.
References handle_link_arrival_event(), LINK_ARRIVAL_EVENT, and IrisEvent::type.
void GenericLink::setup (void)
=====================================================================================
Filename: genericLink.cc
Description: Implements the link component. Per link stats can be updated within this.
Version: 1.0 Created: 02/27/2010 11:48:46 PM Revision: none Compiler: gcc
Author: Mitchelle Rasquinha (), mitchelle.rasquinha@gatech.edu Company: Georgia Institute of Technology
=====================================================================================
Definition at line 26 of file genericLink.cc.
References NetworkComponent::address, credits_passed, flits_passed, Component::myId(), NetworkComponent::name, and node_ip.
string GenericLink::toString () const [virtual]
Reimplemented from IrisLink.
Definition at line 77 of file genericLink.cc.
References NetworkComponent::address, IrisLink::input_connection, and IrisLink::output_connection.
Referenced by print_stats().
Member Data Documentation
ullint GenericLink::credits_passed
Definition at line 47 of file genericLink.h.
Referenced by get_credits_utilization(), handle_link_arrival_event(), print_stats(), and setup().
uint GenericLink::cycles
Definition at line 38 of file genericLink.h.
ullint GenericLink::flits_passed
Definition at line 46 of file genericLink.h.
Referenced by get_flits_utilization(), handle_link_arrival_event(), print_stats(), and setup().
bool GenericLink::is_dateline
Definition at line 49 of file genericLink.h.
uint GenericLink::link_id
Definition at line 48 of file genericLink.h.
uint GenericLink::node_ip [private]
Reimplemented from NetworkComponent.
Definition at line 54 of file genericLink.h.
Referenced by setup().
uint GenericLink::stages
Definition at line 39 of file genericLink.h.
The documentation for this class was generated from the following files:
genericLink.h
genericLink.cc