IRIS: Clock Class Reference
Clock Class Reference
#include <clock.h>
Public Member Functions
Clock (double)
void risingEdge ()
void fallingEdge ()
Public Attributes
double frequency
double period
list< tickObjBase * > risingObjs
list< tickObjBase * > fallingObjs
Detailed Description
Definition at line 23 of file clock.h.
Constructor & Destructor Documentation
Clock::Clock (double freq)
Definition at line 7 of file clock.cc.
References fallingEdge(), frequency, Simulator::Now(), period, risingEdge(), and Simulator::Schedule().
Member Function Documentation
void Clock::fallingEdge ()
Definition at line 30 of file clock.cc.
References fallingObjs, Simulator::Now(), period, and Simulator::Schedule().
Referenced by Clock().
void Clock::risingEdge ()
Definition at line 18 of file clock.cc.
References Simulator::Now(), period, risingObjs, and Simulator::Schedule().
Referenced by Clock().
Member Data Documentation
list<tickObjBase*> Clock::fallingObjs
Definition at line 35 of file clock.h.
Referenced by fallingEdge(), and registerClock().
double Clock::frequency
Definition at line 28 of file clock.h.
Referenced by Clock().
double Clock::period
Definition at line 29 of file clock.h.
Referenced by Clock(), fallingEdge(), and risingEdge().
list<tickObjBase*> Clock::risingObjs
Definition at line 33 of file clock.h.
Referenced by registerClock(), and risingEdge().
The documentation for this class was generated from the following files:
clock.h
clock.cc