IRIS: Component Class Reference
Component Class Reference
#include <component.h>
Public Member Functions
Component ()
Component (int lpId)
~Component ()
void setComponentId (int id)
void addInputLink (Link *l)
void addOutputLink (Link *l)
int myId ()
Public Attributes
std::vector< Link * > inLinks
std::vector< Link * > outLinks
Private Attributes
int componentId
Detailed Description
Definition at line 11 of file component.h.
Constructor & Destructor Documentation
Component::Component ()
Definition at line 10 of file component.cc.
References Simulator::registerComponent().
Component::Component (int lpId)
Definition at line 15 of file component.cc.
References Simulator::registerComponent().
Component::~Component ()
Definition at line 5 of file component.cc.
Member Function Documentation
void Component::addInputLink (Link * l)
Definition at line 25 of file component.cc.
References inLinks.
void Component::addOutputLink (Link * l)
Definition at line 30 of file component.cc.
References outLinks.
Referenced by Link::Link().
int Component::myId () [inline]
Definition at line 24 of file component.h.
References componentId.
Referenced by RouterVcMP::init(), RouterReqReply::init(), GenericRouterPhy::init(), GenericRouter4Stg::init(), NetworkComponent::NetworkComponent(), McFrontEnd::setup(), GenericTracePktGen::setup(), GenericSink::setup(), GenericRPG::setup(), GenericPktGen::setup(), GenericLink::setup(), GenericInterfacePhy::setup(), GenericInterfaceNB::setup(), and GenericFlatMc::setup().
void Component::setComponentId (int id)
Definition at line 20 of file component.cc.
References componentId.
Referenced by Simulator::registerComponent().
Member Data Documentation
int Component::componentId [private]
Definition at line 14 of file component.h.
Referenced by myId(), and setComponentId().
std::vector<Link*> Component::inLinks
Definition at line 16 of file component.h.
Referenced by addInputLink().
std::vector<Link*> Component::outLinks
Definition at line 17 of file component.h.
Referenced by addOutputLink().
The documentation for this class was generated from the following files:
component.h
component.cc