IRIS: manifold_simmc.cc File Reference
manifold_simmc.cc File Reference
#include <string>
#include <string.h>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdlib>
#include <fstream>
#include <map>
#include "../../kernel/component.h"
#include "../../kernel/simulator.h"
#include "../../util/config_params.h"
#include "../../util/mc_constants.h"
#include "../../simIris/data_types/impl/irisEvent.h"
#include "../../memctrl/request.h"
#include "../../memctrl/request_handler.h"
#include "../../memctrl/bus_handler.h"
#include "../../memctrl/bus.h"
#include "../../memctrl/dram.h"
#include "../../memctrl/refresh_manager.h"
#include "../../memctrl/response_handler.h"
#include "../../memctrl/MC.h"
#include "../../memctrl/mshr_standalone.h"
Functions
void iris_process_options (int argc, char *argv[])
void dump_configuration (void)
bool GetNextRequest (Request *req, unsigned int *index)
int main (int argc, char **argv)
Variables
vector< MSHR_SA_H * > mshrHandler
Function Documentation
void dump_configuration (void)
Definition at line 44 of file manifold_simiris.cc.
References BANK_BITS, buffer_size, COLUMN_SIZE, concentration, credits, do_request_reply_network, do_two_stage_router, grid_size, links, max_phy_link_bits, max_sim_time, MC_ADDR_BITS, mc_model_string, mc_positions, mc_response_pkt_payload_length, mean_irt, msg_type_string, NETWORK_ADDRESS_BITS, NETWORK_COMMAND_BITS, NETWORK_THREADID_BITS, network_type, no_mcs, no_msg_classes, no_nodes, NO_OF_BANKS, NO_OF_COLUMNS, no_of_cores, NO_OF_RANKS, NO_OF_ROWS, NO_OF_THREADS, pkt_payload_length, ports, rc_method, router_model_string, routing_scheme, stat_print_level, sw_arbitration, sw_arbitration_scheme, terminal_model_string, terminal_msg_class_string, THREAD_BITS_POSITION, traces, and vcs.
Referenced by main().
bool GetNextRequest (Request * req, unsigned int * index)
Definition at line 150 of file manifold_simmc.cc.
References mshrHandler, and NO_OF_THREADS.
void iris_process_options (int argc, char * argv[])
Definition at line 251 of file manifold_fullsim.cc.
References addr_map_scheme_string, BANK_BITS, buffer_size, COLUMN_SIZE, cores_per_node, credits, data, do_two_stage_router, dram_page_policy_string, FCFS, grid_size, links, MAX_BUFFER_SIZE, MAX_CMD_BUFFER_SIZE, max_phy_link_bits, max_sim_time, MC_ADDR_BITS, mc_positions, mc_scheduling_algorithm_string, msg_type_string, MSHR_SIZE, NEGATIVE_FIRST, NETWORK_ADDRESS_BITS, NETWORK_COMMAND_BITS, NETWORK_THREADID_BITS, no_mcs, no_nodes, NO_OF_BANKS, NO_OF_CHANNELS, NO_OF_COLUMNS, NO_OF_RANKS, NO_OF_ROWS, NO_OF_THREADS, NORTH_LAST, NORTH_LAST_NON_MINIMAL, ODD_EVEN, ONE_FLIT_REQ, output_path, ports, print_setup, priority_msg_type, PRIORITY_REQ, rc_method, RESPONSE_BUFFER_SIZE, RESPONSE_PKT, ROUND_ROBIN, ROUND_ROBIN_PRIORITY, routing_scheme, sw_arbitration, sw_arbitration_scheme, THREAD_BITS_POSITION, traces, vcs, WEST_FIRST, word, and XY.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 52 of file manifold_simmc.cc.
References CONTINUE, dump_configuration(), init_dram_timing_parameters(), iris_process_options(), max_sim_time, mshrHandler, NO_OF_THREADS, Simulator::Now(), Simulator::Run(), Simulator::Schedule(), Simulator::StopAt(), trace_name, traces, and IrisEvent::type.
Variable Documentation
vector<MSHR_SA_H*> mshrHandler
Definition at line 46 of file manifold_simmc.cc.
Referenced by GetNextRequest(), and main().