IRIS: manifold_simiris.cc File Reference
manifold_simiris.cc File Reference
#include "topology.h"
#include "mesh.h"
#include "torus.h"
#include "ring.h"
#include "visual.h"
#include "../../simIris/data_types/impl/flit.h"
#include "../../util/stats.h"
#include "../../simIris/data_types/impl/highLevelPacket.h"
#include "../../util/genericData.h"
#include "../../util/config_params.h"
#include "../../memctrl/mshr.cc"
#include <string.h>
#include <sys/time.h>
#include <algorithm>
Functions
void interface_simiris (ullint)
void dump_configuration (void)
void print_access_counts ()
int main (int argc, char *argv[])
Variables
unsigned long int net_pack_info [8][8]
Topology * topology_ptr = NULL
Function Documentation
void dump_configuration (void)
Definition at line 44 of file manifold_simiris.cc.
References BANK_BITS, buffer_size, COLUMN_SIZE, concentration, credits, do_request_reply_network, do_two_stage_router, grid_size, links, max_phy_link_bits, max_sim_time, MC_ADDR_BITS, mc_model_string, mc_positions, mc_response_pkt_payload_length, mean_irt, msg_type_string, NETWORK_ADDRESS_BITS, NETWORK_COMMAND_BITS, NETWORK_THREADID_BITS, network_type, no_mcs, no_msg_classes, no_nodes, NO_OF_BANKS, NO_OF_COLUMNS, no_of_cores, NO_OF_RANKS, NO_OF_ROWS, NO_OF_THREADS, pkt_payload_length, ports, rc_method, router_model_string, routing_scheme, stat_print_level, sw_arbitration, sw_arbitration_scheme, terminal_model_string, terminal_msg_class_string, THREAD_BITS_POSITION, traces, and vcs.
Referenced by main().
void interface_simiris (ullint)
int main (int argc, char * argv[])
Definition at line 117 of file manifold_simiris.cc.
References addr_map_scheme, addr_map_scheme_string, BANK_BITS, buffer_size, CACHELINE_INTERLEAVING, CLOSE_PAGE_POLICY, COLUMN_SIZE, concentration, Topology::connect_interface_processor(), Topology::connect_interface_routers(), Topology::connect_routers(), credits, data, do_request_reply_network, do_two_stage_router, dram_page_policy, dram_page_policy_string, dump_configuration(), FC_FS, FCFS, FLAT_MC, FR_FCFS, GENERIC, GENERIC_MC, GENERIC_PKTGEN, grid_size, IrisStats::init(), Topology::init(), init_dram_timing_parameters(), Topology::interfaces, istat, Topology::link_a, Topology::link_b, links, LOCAL_ADDR_MAP, MAX_BUFFER_SIZE, MAX_CMD_BUFFER_SIZE, max_phy_link_bits, Topology::max_sim_time, max_sim_time, MC_ADDR_BITS, mc_model, mc_model_string, mc_positions, mc_response_pkt_payload_length, mc_scheduling_algorithm, mc_scheduling_algorithm_string, mean_irt, msg_type_string, MSHR_SIZE, NEGATIVE_FIRST, net_pack_info, NETWORK_ADDRESS_BITS, NETWORK_COMMAND_BITS, network_frequency, NETWORK_THREADID_BITS, network_type, no_mcs, no_msg_classes, no_nodes, NO_OF_BANKS, NO_OF_CHANNELS, NO_OF_COLUMNS, no_of_cores, NO_OF_RANKS, NO_OF_ROWS, NO_OF_THREADS, NO_SCHEME, NORTH_LAST, NORTH_LAST_NON_MINIMAL, ODD_EVEN, ONE_FLIT_REQ, OPEN_PAGE_POLICY, output_path, PAGE_INTERLEAVING, PAR_BS, PERMUTATION, PHYSICAL, pkt_payload_length, ports, print_access_counts(), print_setup, Topology::print_stats(), priority_msg_type, PRIORITY_REQ, Topology::processors, rc_method, RESPONSE_BUFFER_SIZE, RESPONSE_PKT, RING_ROUTING, ROUND_ROBIN, ROUND_ROBIN_PRIORITY, router_model, router_model_string, Topology::routers, routing_scheme, Simulator::Run(), Topology::setup(), sim_start_time, SINK, Simulator::StopAt(), sw_arbitration, sw_arbitration_scheme, terminal_model, terminal_model_string, terminal_msg_class, terminal_msg_class_string, THREAD_BITS_POSITION, TORUS_ROUTING, TPG, trace_name, traces, vcs, VIRTUAL, WEST_FIRST, word, and XY.
void print_access_counts ()
Definition at line 105 of file manifold_simiris.cc.
References IrisStats::get_total_credits_passed(), IrisStats::get_total_flits_passed(), IrisStats::get_total_ib_cycles(), IrisStats::get_total_rc_cycles(), IrisStats::get_total_sa_cycles(), IrisStats::get_total_st_cycles(), IrisStats::get_total_vca_cycles(), and istat.
Referenced by main().
Variable Documentation
unsigned long int net_pack_info[8][8]
Definition at line 38 of file manifold_simiris.cc.
Referenced by main().
Topology* topology_ptr = NULL
Definition at line 42 of file manifold_simiris.cc.